### ISSUE TITLE
Custom Theme for Battlelog?

### ISSUE THREAD

**Issue by Arbiterz** [brainfoolong/better-battlelog#6]
Cant find a guide on creating a custom theme for Battelog. Wondering if anyone can help me out here

**Comment by brainfoolong** [comment]
Hi. There is no real "guide" on how the create a custom theme. You have to learn CSS, for which millions of tutorials exist out there. Then you need a browser extension that allow you to add your custom CSS to a page. Maybe Stylish -> https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe

Specifically for battlelog, there are existing themes, where you can steal some css code from. They will be a good starting point. -> https://github.com/brainfoolong/better-battlelog/tree/master/themes

Using Better Battlelog browser extension for this case isn't recommended anymore, but still possible, as it contains a css editor.

Greetz

**Comment by Arbiterz** [comment]
Yo that was a fast response. Would it be possible to have a custom animated background for battlelog?

**Comment by brainfoolong** [comment]
With CSS only it's limited to images only, which can be animated in a limited way. Otherwise you need javascript as well, which is a whole new level. Example: https://www.w3schools.com/howto/howto_css_fullscreen_video.asp

Anyway, this is not the right place to ask further about such help. It is not Better Battlelog related. You have to learn website manipulation in general, independent of BBLog.

Have a nice day, i close this.
